### ISSUE TITLE
functions in FSA package

### ISSUE THREAD

**Issue by LCieps** [droglenc/FSA#53]
I have successfully been (as recently as Monday 11/26) working with the FSA package. Today, however, none of the functions will run, even in the example dataset and code. Is there a bug or was there an update to the FSA package?

**Comment by droglenc** [comment]
Lcieps,

No updates or releases. Also updates will not effect your computer unless you choose to update the package, which I assume you did not.

You have not given me much to go on there, but a guess is that you forgot to attach the `FSA` package prior to trying to use one of its functions. In other words, make sure you do `library(FSA)` early in your script. Alternatively, you did type this but received an error for some reason (such that the package was not attached).

Let me know (with more details) if you continue to have problems.

**Comment by LCieps** [comment]
I apologize for the lack of detail. I had loaded the FSA package using the command library(FSA). After more troubleshooting I realized the embedded (or associated?) package Rcpp failed to load when loading FSA. The solution was to manually install Rcpp. 

Thank you.

**Comment by droglenc** [comment]
LCieps,

That makes sense ... `FSA` would not load in the end if the required `Rcpp` package did not load properly. I am not sure why but I have had similar problems with `Rcpp`, but once I manually installed it then `FSA` worked fine.

Thanks for the follow-up.
