### ISSUE TITLE
Negative value while using function to calculate Length at First Maturity!

### ISSUE THREAD

**Issue by sonhnrimf** [droglenc/FSA#59]
Hello Dr. Ogle,

I'm Sean,a junior biologist from Vietnam. Firstly, i want to thank you for this amazing package. It helped us a lot in our study and research.
I used FSA package to calculate the Length at first Maturity, following your steps has been described in your article (fishR Vignette - Maturity Schedules, Dec 16,2013). but got the negative results.
I tried again using equation with another software, the result i got was possitive.  I could not figure it out why.
Here's my code. attach files also included.
```
>glmFselep<-glm(Maturity~FL,data=`Selaroides leptolepis TNB 2019 I9.csv`,family=binomial)
>lr <- function(cf,p) (log(p/(1-p))-cf[1])/cf[2]
>(L50 <- lr(coef(glm1),0.5)) 
(Intercept) 
-586.1651
```
[Selaroides leptolepis TNB 2019 I9.txt](https://github.com/droglenc/FSA/files/4026789/Selaroides.leptolepis.TNB.2019.I9.txt)

Thank you for your time!

Regards from Vietnam,
Sean

**Comment by droglenc** [comment]
Sean,

Thanks for the message. First, note that your example is not purely reproducible without the code to read in your data and also noting that in your third line there is no object called `glm1`. However, those were not too much work to fix.

The bigger issue seems to be the "shape" of your data. A `fitPlot()` of your `glmFselep` object shows that the proportion mature increases from about 70 mm to 150 mm, but then there are no fish sampled between 150 and 190 mm, and then fish between 190 and 220 mm tend not to be mature with the proportion mature increasing after 230 mm. In other words, the binomial GLM is looking for a generally increasing (or decreasing) curve and yours basically increases, then drops to zero, and then increases again. Thus, the GLM basically fits a very flat line that starts well above 50% mature for your data.

Do you have two groups of fish (those less than 150 mm and those greater than 190 mm)???

I filtered the data to those fish less than 150 mm just to demonstrate that the method will work with data that is generally increasing.

```
d <- read.table("https://github.com/droglenc/FSA/files/4026789/Selaroides.leptolepis.TNB.2019.I9.txt",header=TRUE)
str(d)
glmFselep <- glm(Maturity~FL,data=d,family=binomial)
FSA::fitPlot(glmFselep)

d <- dplyr::mutate(d,lcat10=FSA::lencat(d$FL,w=10))
xtabs(~lcat10+Maturity,data=d)

d2 <- dplyr::filter(d,FL<150)
glmFselep2 <- glm(Maturity~FL,data=d2,family=binomial)
FSA::fitPlot(glmFselep2)

lr <- function(cf,p) (log(p/(1-p))-cf[1])/cf[2]
(L50 <- lr(coef(glmFselep2),0.5)) 
```

I hope that this helps you identify your issue.

**Comment by sonhnrimf** [comment]
Thank you so much, Professor!
The problem has been solved. Thank you for your time!

Best regards,

Sean
