### ISSUE TITLE
Small bug in hist.formula function

### ISSUE THREAD

**Issue by carlostorrescubila** [droglenc/FSA#62]
The parameter `freq` sometimes does not work. When you set it `FALSE` it works on plot, but the y-scale does not change and you can't see the bars. Probably it happends because you take always the `counts` value of `hist.default` and you have to take `density` values when `freq = FALSE`.

**Comment by droglenc** [comment]
Thanks, @carlostorrescubila ... I will try to fix this.

Note to self ... here is the issue ... compare these two outpus

```
hist(Sepal.Length~Species,data=iris)
hist(Sepal.Length~Species,data=iris,freq=FALSE)
```

**Comment by droglenc** [comment]
@carlostorrescubila ... this should be fixed in the development version. Let me know if you still have issues. Thanks again.
