### ISSUE TITLE
internal function to check `conf.level=` argument

### ISSUE THREAD

**Issue by droglenc** [droglenc/FSA#66]
Several functions use `conf.level=` and most of them have the following "checking" code ...

```
if (conf.level<=0 | conf.level>=1) STOP("'conf.level' must be between 0 and 1")
```

I suggest creating an internal function (to be in FSAInternals.R) called `iCheckConfLevel()` that will first check to make sure `conf.level` is `numeric` and then perform this check. It may look like this ...

```
iCheckConfLevel <- function(conf.level) {
  if (!is.numeric(conf.level)) STOP("'conf.level' must be numeric.")
  if (conf.level<=0 | conf.level>=1) STOP("'conf.level' must be between 0 and 1")
```

Functions that currently perform this check that could be replaced with `iCheckConfLevel()` are ...
- [x] `bootCase()`
- [x] `catchCurve()`
- [x] `chapmanRobson()`
- [x] `binCI()`, `hyperCI()`, `poiCI()` (in CIDists.R)
- [x] `depletion()`
- [x] `mrClosed()`
- [x] `mrOpen()`
- [x] `removal()`

Functions that may use `conf.level=` but don't appear to check anything are ...
- [ ] `compSlopes()` and `compIntercepts()` (in comparisonsDVR.R)
- [x] `fitPlot()`
- [x] `psdCalc()`
- [x] `psdCI()`

**Comment by jcdoll79** [comment]
working on issue in "conf_level" branch.

**Comment by jcdoll79** [comment]
@droglenc I believe I have addressed the conf.check at all necessary locations and added new tests for each function that was affected. I do not have a comparisonsDVR.R file and it looks like the compSlopes() and compIntercepts() functions were removed based on FSA-defunct.R. Would they be in another location? If not, I'll do one last check and submit a pull request.

**Comment by droglenc** [comment]
@jcdoll79 When I made those functions defunct, I took them out of `FSA` (and put them in `FSAmisc`, for safe keeping). You don't need to do anything more with them. I should have commented about this on this issue earlier. Sorry. Thanks.
