### ISSUE TITLE
PSDlit sources

### ISSUE THREAD

**Issue by daveglover** [droglenc/FSA#76]
Any reason that the PSDlit table does not list the source, similar to WSlit? I was able to track confirm where most came from but had trouble figuring out exactly where a few came from. 

Thanks!

**Comment by droglenc** [comment]
Dave,

This was one of the first functions I wrote and all of the length values came from the same synthetic source, so I likely did not think about adding it. This is a good suggestion and I will work on adding them for the next release. Thanks for asking.

**Comment by droglenc** [comment]
Re-opening so I remember to fix this.

**Comment by droglenc** [comment]
In the next version this will work as such ...

```
psdVal("Bluegill",showJustSource=TRUE)
```

To have he source included with a regular call would require major changes because `psdVal()` returns a numeric matrix which cannot have columns of different types. This will be a compromise.
